config/routes.rb
Rails.application.routes.draw do

  #-------------------------Restful Routes-------------------------------#
  resources :attacks, only: [:index, :show, :new, :create, :edit, :update]
  delete '/attacks/:id/delete', to: 'attacks#destroy', as: 'destroy_attack'
  resources :birds, only: [:index, :show, :new, :create, :edit, :update]
  delete '/birds/:id/delete', to: 'birds#destroy', as: 'destroy_bird'
  resources :doctors, only: [:index, :show, :new, :create, :edit, :update]
  delete '/doctors/:id/delete', to: 'doctors#destroy', as: 'destroy_doctor'
  resources :foods, only: [:index, :show, :new, :create, :edit, :update]
  delete '/foods/:id/delete', to: 'foods#destroy', as: 'destroy_food'
  resources :children, only: [:index, :show, :new, :create, :edit, :update]
  delete '/children/:id/delete', to: 'children#destroy', as: 'destroy_children'

  #------------------------Custom Routes---------------------------------#
  get '/play', to:'children#home', as: 'play'
  post '/north', to: 'children#north'
  post '/east', to: 'children#east'
  post '/west', to: 'children#west'
  post '/south', to: 'children#south'
  post '/food', to: 'children#food'
  post '/doctor', to: 'children#doctor'

  #----------------------Authentication & Sessions------------------------#
  get "/", to: "sessions#new", as: "login"
  post "/", to: "sessions#create", as: "sessions"
  post '/start_over', to: 'children#start_over'

  get '/unauthorized', to: 'children#unauthorized'

end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  before_action :admin?, only: [:index]
  before_action :reset_hp_cookies, only: [:north, :south, :east, :west, :food]
  before_action :reset_hunger_cookies, only: [:north, :south, :east, :west, :doctor]
  before_action :reset_infection_cookies, only: [:north, :south, :east, :west, :doctor, :food]
  #@current_user = nil

  def home
  end

  def game_mechanics
    @kb = false
    doctor_exist?
    food_exist?
    if bird_attack?
      @bird = Bird.all.sample
      @bird_damage = rand(5..@bird.attack)
      @current_user.hp -= @bird_damage
      @current_user.save
      if @bird_damage >= @current_user.hp
        @kb = true
      else
        @kb = false
      end
      @current_attack = Attack.create(bird_id: @bird.id, child_id: @current_user.id, damage_done: @bird_damage, killing_blow: @kb)
        if @bird.sickness && !@current_user.sickness
          @current_user.sickness = [true, false].sample
          @current_user.save
          if @current_user.sickness
            session[:infection] = true
          end
        end
    end
    if @current_user.sickness
      @sickness = rand(1..5)
      @current_user.hp -= @sickness
      @current_user.save
    end
    @current_user.hunger += rand(2..10)
    @current_user.save
    if alive?
      render :home
    else
      render :death
    end
  end

  def unauthorized
  end

  def food
    @food = Food.all.sample
    @current_user.hunger -= @food.hunger_decrease
    session[:hunger_decrease] = @food.hunger_decrease
    if @current_user.hunger < 0
      @current_user.hunger = 0
    end
    @current_user.save
    redirect_to play_path
  end

  def doctor
    @doctor = Doctor.all.sample
    @current_user.hp += @doctor.hp_increase
    session[:hp_increase] = @doctor.hp_increase
    @current_user.sickness = false
    if @current_user.hp > 100
      @current_user.hp = 100
    end
    @current_user.save
    redirect_to play_path
  end

  def start_over
    @current_user.hp = rand(90..100)
    @current_user.hunger = rand(1..5)
    @current_user.location_x = rand(2)
    @current_user.location_y = rand(3)
    @current_user.sickness = false
    @current_user.save
    @kb = false
    redirect_to @current_user
  end

  #Directionals ------------------------------------

  def north
    @current_user.location_x += 1
    @current_user.save
    game_mechanics
  end

  def east
    @current_user.location_y -= 1
    @current_user.save
    game_mechanics
  end

  def west
    @current_user.location_y += 1
    @current_user.save
    game_mechanics
  end

  def south
    @current_user.location_x -= 1
    @current_user.save
    game_mechanics
  end

  #------------------------------------------------------

  #Restful Routes ---------------------------------------

  def index
      @children = Child.all
  end

  def show
    @child = Child.find(params[:id])
  end

  def new
    @child = Child.new
    #MUST RANDOMLY GENERATE HP, HUNGER, X, AND Y
    @hp = rand(90..100)
    @hunger = rand(1..5)
    @location_x = rand(2)
    @location_y = rand(3)
  end

  def create

    @child = Child.create(child_params)
    if @child.valid?
      redirect_to '/'
    else
      flash[:error] = @child.errors.full_messages
      render :new
    end
  end

  def edit
    @child = Child.find(params[:id])
  end

  def update
    @child = Child.find(params[:id])
    @child.update(child_params)
    redirect_to @child
  end

  def destroy
    @child = Child.find(params[:id])
    @child.destroy
    redirect_to '/'
  end

 #----------------------------------------------

  private
  def child_params
    params.require(:child).permit(:name, :password, :hp, :hunger, :location_x, :location_y)
  end

  def doctor_exist?
    @doctor_exist = [true, false, false, false, true, false].sample
  end

  def food_exist?
    @food_exist = [true, false, false, false].sample
  end

  def bird_attack?
    @bird_attack = [true, false, false, true, true].sample
  end

  def alive?
    if @current_user.hp <= 0 || @current_user.hunger >= 100
      false
    else
      true
    end
  end

  def reset_hp_cookies
    session[:hp_increase] = nil
  end

  def reset_hunger_cookies
    session[:hunger_decrease] = nil
  end

  def reset_infection_cookies
    session[:infection] = false
  end



end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/views/children/death.html.erb
<h1>You have died.</h1> <br>
<% if @current_user.hp <= 0 && @kb == false%>
<h2>You have been killed by sickness.</h2>
<% elsif @current_user.hp <= 0 && @kb == true%>
<h2>You have been killed by a <%= @bird.species %>.</h2>
<% elsif @current_user.hunger >= 100 %>
<h2>You have died of hunger.</h2>
<% end %>
<%= image_tag ("https://upload.wikimedia.org/wikipedia/commons/8/85/Skull_and_Crossbones.png"), size: "300x250" %> <br>
<%= form_tag("/start_over") do %>
  <%= submit_tag("Start Over") %>
<% end %>

app/views/children/edit.html.erb
<h2>Edit Child Details</h2>

<%= form_for @child do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :password %>
<%= f.text_field :password %>
<%= f.submit "Submit Child" %>
<% end %>

app/views/children/home.html.erb
<div class="bird-display">
  <% if @bird_attack %>
    <%= render "/gameboard/bird_attack" %>
  <% end %>
</div>

<div class="player-display">
  <%= render "/gameboard/options" %>
  <%= render "/gameboard/navigation" %>
</div>

app/views/children/index.html.erb
<h2>All User Accounts</h2>

<% @children.each do |child| %>
<%= link_to child.name, child_path(child) %><br/>
<% end %>
<br/>
<%= link_to "Add A New User", new_child_path%>

app/views/children/login.html.erb
<h2>Welcome to Bird Attack</h2>

<form action="/" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  Name: <input type="text" name="name">
  Password: <%= password_field_tag 'password' %>
  <input type="submit" value="Submit">
</form>


<%= link_to "Create a New Account", new_child_path %>

app/views/children/new.html.erb
<h2>Add a New Child</h2>

<%= form_for @child do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.number_field :hp, value: @hp, hidden: true %>
<%= f.number_field :hunger, value: @hunger, hidden: true %>
<%= f.number_field :location_x, value: @location_x, hidden: true %>
<%= f.number_field :location_y, value: @location_y, hidden: true %>
<%= f.submit "Submit Child" %>
<% end %>

app/views/children/show.html.erb
<h2>Child Details</h2>

<label>Name: <%= @child.name %></label>
<br/>
<label>HP: <%= @child.hp %></label>
<br/>
<label> Hunger: <%= @child.hunger %></label>
<br/>
<br/>
<%= link_to "Edit Child Details", edit_child_path%>
<br/>
<%= link_to "Delete Child Account", destroy_children_path, method: :delete %>
<br>
<%= link_to "Start Over", "/start_over", method: :post %>
<br>
<%= link_to "Play Game", play_path %>
<br>
<br>
<% if @current_user.admin %>
  <%= link_to "See Birds", birds_path %> <br>
  <%= link_to "See Doctors", doctors_path %> <br>
  <%= link_to "See Food", foods_path %> <br>
  <%= link_to "See Attacks", attacks_path %> <br>
  <%= link_to "See Children", children_path %> <br>
<% end %>

app/views/children/unauthorized.html.erb
<h1>You aren't authorized to see this page.</h1>
<br>
<br>
<%= link_to "Play Game", play_path %> <br>
<%= link_to "See Stats", child_path(@current_user) %>