config/routes.rb
Rails.application.routes.draw do

  #-------------------------Restful Routes-------------------------------#
  resources :attacks, only: [:index, :show, :new, :create, :edit, :update]
  delete '/attacks/:id/delete', to: 'attacks#destroy', as: 'destroy_attack'
  resources :birds, only: [:index, :show, :new, :create, :edit, :update]
  delete '/birds/:id/delete', to: 'birds#destroy', as: 'destroy_bird'
  resources :doctors, only: [:index, :show, :new, :create, :edit, :update]
  delete '/doctors/:id/delete', to: 'doctors#destroy', as: 'destroy_doctor'
  resources :foods, only: [:index, :show, :new, :create, :edit, :update]
  delete '/foods/:id/delete', to: 'foods#destroy', as: 'destroy_food'
  resources :children, only: [:index, :show, :new, :create, :edit, :update]
  delete '/children/:id/delete', to: 'children#destroy', as: 'destroy_children'

  #------------------------Custom Routes---------------------------------#
  get '/play', to:'children#home', as: 'play'
  post '/north', to: 'children#north'
  post '/east', to: 'children#east'
  post '/west', to: 'children#west'
  post '/south', to: 'children#south'
  post '/food', to: 'children#food'
  post '/doctor', to: 'children#doctor'

  #----------------------Authentication & Sessions------------------------#
  get "/", to: "sessions#new", as: "login"
  post "/", to: "sessions#create", as: "sessions"
  post '/start_over', to: 'children#start_over'

  get '/unauthorized', to: 'children#unauthorized'

end

app/models/attack.rb
class Attack < ApplicationRecord
  belongs_to :child
  belongs_to :bird
end

app/controllers/attacks_controller.rb
class AttacksController < ApplicationController
  before_action :admin?

  def index
    @attacks = Attack.all
  end

  def show
    @attack = Attack.find(params[:id])
  end

  def new
    @attack = Attack.new
    @children = Child.all
    @birds = Bird.all
  end

  def create
    @attack = Attack.create(attack_params)
    redirect_to @attack
  end

  def edit
    @attack = Attack.find(params[:id])
    @children = Child.all
    @birds = Bird.all
  end

  def update
    @attack = Attack.find(params[:id])
    @attack.update(attack_params)
    redirect_to @attack
  end

  def destroy
    @attack = Attack.find(params[:id])
    @attack.destroy
    redirect_to birds_path
  end

  private
  def attack_params
    params.require(:attack).permit(:child_id, :bird_id)
  end


end

app/helpers/attacks_helper.rb
module AttacksHelper
end

app/views/attacks/edit.html.erb
<h2>Edit Attack Details</h2>

<%= form_for @attack do |f| %>
<%= f.label :child_id %>
<%= f.collection_select :child_id, @children, :id, :name %>
<%= f.label :bird_id %>
<%= f.collection_select :bird_id, @birds, :id, :species %>
<%= f.submit "Submit Attack" %>
<% end %>

app/views/attacks/index.html.erb
<h2>All Attack Encounters</h2>

<% @attacks.each do |attack| %>
<%= link_to "#{attack.created_at} - #{attack.child.name} - #{attack.bird.species}", attack_path(attack) %><br/>
<% end %>
<br/>
<%= link_to "Add A New Attack Encounter", new_attack_path%>

app/views/attacks/new.html.erb
<h2>Add a New Attack Instance</h2>

<%= form_for @attack do |f| %>
<%= f.label :child_id %>
<%= f.collection_select :child_id, @children, :id, :name %>
<%= f.label :bird_id %>
<%= f.collection_select :bird_id, @birds, :id, :species %>
<%= f.submit "Submit Attack" %>
<% end %>

app/views/attacks/show.html.erb
<h2>Attack Details</h2>

<label>Date/Time of Attack: <%= @attack.created_at%></label>
<br/>
<label>Username: <%= link_to @attack.child.name, child_path(@attack.child) %></label>
<br/>
<label>Bird: <%= link_to @attack.bird.species, bird_path(@attack.bird) %></label>
<br/>
<label>Killing Blow?: <%= @attack.killing_blow%> </label>
<br/>
<br/>
<%= link_to "Edit Attack Details", edit_attack_path%>
<br/>
<%= link_to "Delete Attack Occurence", destroy_attack_path, method: :delete%>