config/routes.rb
Rails.application.routes.draw do

  #-------------------------Restful Routes-------------------------------#
  resources :attacks, only: [:index, :show, :new, :create, :edit, :update]
  delete '/attacks/:id/delete', to: 'attacks#destroy', as: 'destroy_attack'
  resources :birds, only: [:index, :show, :new, :create, :edit, :update]
  delete '/birds/:id/delete', to: 'birds#destroy', as: 'destroy_bird'
  resources :doctors, only: [:index, :show, :new, :create, :edit, :update]
  delete '/doctors/:id/delete', to: 'doctors#destroy', as: 'destroy_doctor'
  resources :foods, only: [:index, :show, :new, :create, :edit, :update]
  delete '/foods/:id/delete', to: 'foods#destroy', as: 'destroy_food'
  resources :children, only: [:index, :show, :new, :create, :edit, :update]
  delete '/children/:id/delete', to: 'children#destroy', as: 'destroy_children'

  #------------------------Custom Routes---------------------------------#
  get '/play', to:'children#home', as: 'play'
  post '/north', to: 'children#north'
  post '/east', to: 'children#east'
  post '/west', to: 'children#west'
  post '/south', to: 'children#south'
  post '/food', to: 'children#food'
  post '/doctor', to: 'children#doctor'

  #----------------------Authentication & Sessions------------------------#
  get "/", to: "sessions#new", as: "login"
  post "/", to: "sessions#create", as: "sessions"
  post '/start_over', to: 'children#start_over'

  get '/unauthorized', to: 'children#unauthorized'

end

app/models/food.rb
class Food < ApplicationRecord
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :admin?
  
  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
    #RANDOMLY GENERATE X AND Y COORDINATES
    @location_x = rand(2)
    @location_y = rand(3)
  end

  def create
    @food = Food.create(food_params)
    redirect_to @food
  end

  def edit
    @food = Food.find(params[:id])
  end

  def update
    @food = Food.find(params[:id])
    @food.update(food_params)
    redirect_to @food
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to birds_path
  end

  private
  def food_params
    params.require(:food).permit(:hunger_decrease, :location_x, :location_y)
  end

end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/edit.html.erb
<h2>Edit Food Details</h2>

<%= form_for @food do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit "Submit Food" %>
<% end %>

app/views/foods/index.html.erb
<h2>All the Foooooods</h2>

<% @foods.each do |food| %>
<%= link_to food.name, food_path(food) %><br/>
<% end %>
<br/>
<%= link_to "Add A New Food", new_food_path%>

app/views/foods/new.html.erb
<h2>Add New Food</h2>

<%= form_for @food do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.number_field :location_x, value: @location_x, hidden: true %>
<%= f.number_field :location_y, value: @location_y, hidden: true %>
<%= f.submit "Submit Food" %>
<% end %>

app/views/foods/show.html.erb
<h2>Food Details</h2>

<label>Name: <%= @food.name %></label>
<br/>
<label>Hunger Decrease: <%= @food.hunger_decrease %></label>
<br/>
<br/>
<label>X Coordinate: <%= @food.location_x %></label>
<br/>
<label>Y Coordinate: <%= @food.location_y %></label>
<br/>
<br/>

<%= link_to "Edit Food Details", edit_food_path%>
<br/>
<%= link_to "Delete Food", destroy_food_path, method: :delete %>