config/routes.rb
Rails.application.routes.draw do

  #-------------------------Restful Routes-------------------------------#
  resources :attacks, only: [:index, :show, :new, :create, :edit, :update]
  delete '/attacks/:id/delete', to: 'attacks#destroy', as: 'destroy_attack'
  resources :birds, only: [:index, :show, :new, :create, :edit, :update]
  delete '/birds/:id/delete', to: 'birds#destroy', as: 'destroy_bird'
  resources :doctors, only: [:index, :show, :new, :create, :edit, :update]
  delete '/doctors/:id/delete', to: 'doctors#destroy', as: 'destroy_doctor'
  resources :foods, only: [:index, :show, :new, :create, :edit, :update]
  delete '/foods/:id/delete', to: 'foods#destroy', as: 'destroy_food'
  resources :children, only: [:index, :show, :new, :create, :edit, :update]
  delete '/children/:id/delete', to: 'children#destroy', as: 'destroy_children'

  #------------------------Custom Routes---------------------------------#
  get '/play', to:'children#home', as: 'play'
  post '/north', to: 'children#north'
  post '/east', to: 'children#east'
  post '/west', to: 'children#west'
  post '/south', to: 'children#south'
  post '/food', to: 'children#food'
  post '/doctor', to: 'children#doctor'

  #----------------------Authentication & Sessions------------------------#
  get "/", to: "sessions#new", as: "login"
  post "/", to: "sessions#create", as: "sessions"
  post '/start_over', to: 'children#start_over'

  get '/unauthorized', to: 'children#unauthorized'

end

app/models/bird.rb
class Bird < ApplicationRecord
  has_many :attacks
  has_many :children, through: :attacks
end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  before_action :admin?
  
  def index
    @birds = Bird.all
  end

  def show
    @bird = Bird.find(params[:id])
  end

  def new
    @bird = Bird.new
  end

  def create
    @bird = Bird.create(bird_params)
    redirect_to @bird
  end

  def edit
    @bird = Bird.find(params[:id])
  end

  def update
    @bird = Bird.find(params[:id])
    @bird.update(bird_params)
    redirect_to @bird
  end

  def destroy
    @bird = Bird.find(params[:id])
    @bird.destroy
    redirect_to birds_path
  end

  private
  def bird_params
    params.require(:bird).permit(:species, :sickness, :attack)
  end

end

app/helpers/birds_helper.rb
module BirdsHelper
end

app/views/birds/edit.html.erb
<h2>Edit Bird Details</h2>

<%= form_for @bird do |f| %>
<%= f.label :species %>
<%= f.text_field :species %>
<%= f.label :sickness %>
<%= f.text_field :sickness %>
<%= f.label :attack %>
<%= f.text_field :attack %>
<%= f.submit "Submit Bird" %>
<% end %>

app/views/birds/index.html.erb
<h2>All Birds</h2>

<% @birds.each do |bird| %>
<%= link_to bird.species, bird_path(bird) %><br/>
<% end %>
<br/>
<%= link_to "Add A New Bird", new_bird_path%>
<%= link_to "Return to current user", user_path(@current_user) %>

app/views/birds/new.html.erb
<h2>Add a New Bird</h2>

<%= form_for @bird do |f| %>
<%= f.label :species %>
<%= f.text_field :species %>
<%= f.label :sickness %>
<%= f.text_field :sickness %>
<%= f.label :attack %>
<%= f.text_field :attack %>
<%= f.submit "Submit Bird" %>
<% end %>

app/views/birds/show.html.erb
<h2>Bird Details</h2>

<label>Species: <%= @bird.species %></label>
<br/>
<label>Sick?: <%= @bird.sickness %></label>
<br/>
<label>Attack Power: <%= @bird.attack %></label>
<br/>
<br/>
<%= link_to "Edit Bird Details", edit_bird_path%>
<br/>
<%= link_to "Delete Bird", destroy_bird_path, method: :delete %>